module.exports = {
  APP_INIT: 'APP_INIT',
  SET_NETWORK: 'SET_NETWORK',
  SET_WALLET_PRESENT: 'SET_WALLET_PRESENT',
  SET_WALLET: 'SET_WALLET',
  SET_WALLET_PASSCODE: 'SET_WALLET_PASSCODE',
  SET_ETH_BALANCE: 'SET_ETH_BALANCE',
  SET_RBT_BALANCE: 'SET_RBT_BALANCE',
};
